# Generated by Django 4.0.2 on 2022-03-27 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0004_category_product_project_product_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('purchased_date', models.DateTimeField()),
                ('anonymous', models.BooleanField()),
                ('comment', models.CharField(max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='gtin',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.DeleteModel(
            name='Project_Product',
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_product', to='projects.product'),
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_product', to='projects.project'),
        ),
        migrations.AddField(
            model_name='projectproduct',
            name='purchased_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_project_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
